name = "feito-app-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
ALLOWED_ORIGINS = "https://jeancelsosilva-prog.github.io"
VAPID_SUBJECT = "mailto:jeancelsosilva@gmail.com"
VAPID_PUBLIC_KEY = "BH7Lajz0qwN7jW7iy_6rFWA-03yxP1gv012FpqzTXcwGpGvFCXlzVSh42OHMgbw-m08AW9Swv77jsNROPumVvMQ"

[[d1_databases]]
binding = "DB"
database_name = "feito-app-db"
database_id = "440dcebf-ba8d-467b-ae7e-53e6a22c46cc"
migrations_dir = "../migrations"

[triggers]
crons = ["* * * * *", "0 * * * *"]
